### ISSUE TITLE
Multithread / Multisample

### ISSUE THREAD

**Issue by ulaszewski** [meiji-bioinf/heap#2]
Hi
Thanks for this great piece of code. In my case it seems that the multithread option is not working correctly. Ok, I can run 16 samples at a time, but it runs slowly. With 16 CPU for processsing 1/16 samples I get like 3 hrs, when running on only 1 CPU it takes 5 minutes. Do you have any advice on that? The second thing is running 'heap' with multiples samples, I have something like +1k samples, is there a possibility to somehow make heap run with '-i *.bam' parameter, instead of each sample separately? 
Best regards,
Bart

**Comment by Misa33Saito** [comment]
@ulaszewski Thanks for the feedback.
I'm sorry to delay the response to your issue.

The first issue of multithread, heap with the multi thread may require longer calculation time than the single thread run.
For such case, we recommend the single thread run for mining SNPs.
The improved version for the multi thread run will be released in the future.

The second issue of multiple samples, heap cannot use a wildcard(*) for input files, so please enter all file names correctly. 
e.g.) -i 1.bam -i 2.bam ... -i n.bam
